### ISSUE TITLE
Make /delete more human-friendly

### ISSUE THREAD

**Issue by BjoernPetersen** [tim-hat-die-hand-an-der-maus/telegram-bot#75]
The success response is very confusing:

![image](https://user-images.githubusercontent.com/2513555/157188208-1d6a7151-eff0-4e2c-a006-73e6f2d32032.png)

The matching is very bad:

![image](https://user-images.githubusercontent.com/2513555/157188254-bd589d9b-c8ca-49fb-a3b9-4b39b5b1631b.png)

Generally it's not really necessary to repeat the user's input in the response. Also using parameters for telegram commands is very unwieldy and often leads to accidental messages with just the command. We should accept the bare command and send an inline keyboard with options or something.

**Comment by torbencarstens** [comment]
This also removes any ambiguity when deleting a movie (e.g. same name, different year).
I'm not sure whether teloxide provides inline-keyboard support yet.

**Comment by torbencarstens** [comment]
I've started working on this here (yes I can spell thank you very much): https://github.com/tim-hat-die-hand-an-der-maus/telegram-bot/tree/feature/humenFriendlyDelete

I'm honestly unsure how this works in group chats, it does what it should do but not sure about the 'human friendly' and non-spam part.

We should test this out at some point.
